spring:
  application:
    name: admin-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   # nacos 地址
  security:
    user:
      name: admin    # springboot admin登录用户名
      password: admin  #springboot admin登录密码

  #配置邮件报警发送邮箱
  mail:
    host: smtp.exmail.qq.com
    username: zhangyu01@meizhu365.com
    password: xxxxx

  #接收邮件地址
  boot:
    admin:
      notify:
        mail:
          from: zhangyu01@meizhu365.com   # 发件人邮箱
          to: zhangyu01@meizhu365.com     # 收件人邮箱


server:
  port: 8796

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS