server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
        # 自定义事务组名称需要 seata-service 中的对应
        tx-service-group: ${spring.application.name}
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: f6c97b54-1580-4c4a-976e-a87e4060f17d   #注册到指定命名空间
      config:
        server-addr: localhost:8848    #指定配置中心地址
  datasource:
    driver-class-name: com.mysql.jdbc.Driver     #mysql驱动包
    url: jdbc:mysql://localhost:3306/yy_account?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.youyuan.springcloud.alibaba.domain