server:
  port: 9003

spring:
  application:
    name: payment-service-nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #注册中心地址


management:
  endpoints:
    web:
      exposure:
        include: "*"