server:
  port: 8002
spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
    seluth:
      sampler:
        # 采样值介于 0-1 之间 1 表示全部采集
        probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver     #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    register-with-eureka: true            #表示 将自己注册到eureka server  默认是true
    fetch-registry: true                  #是否从eureka server提取已有的注册信息，默认true，单节点无所谓，但是集群必须设置true ribbon才能实现负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #eureka server的地址
  instance:
    instance-id: payment8002       #修改主机在eureka上显示的别名 默认是主机名+端口号  一般生产环境不需要使用
    prefer-ip-address: true        #通过ip注册到eureka上，鼠标放到主机名上可以显示主机的ip地址
    lease-renewal-interval-in-seconds: 1  #调整为服务提供者每隔1秒向注册中心发送一次心跳
    lease-expiration-duration-in-seconds: 2  #调整eureka服务在2秒内没有收到服务提供者发送心跳就从服务注册表中删除服务提供者的地址

mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.youyuan.springcloud.entities    #所有Entity别名类所在的包
