server:
  port: 9527

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
        # 开启从注册中心动态创建路由的功能， 利用微服务名进行路由、
          enabled: true
      routes:
        # payment_routh 路由ID ， 没有固定的规则但是要求唯一，建议配合服务名
        - id: payment_routh
          # 匹配提供服务的路由地址
          #uri: http://localhost:8001
          #指定微服务名称(注册到eureka上的名称 lb代表负载均衡)
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**

        # payment_routh 路由ID ， 没有固定的规则但是要求唯一，建议配合服务名
        - id: payment_routh2
          # 匹配提供服务的路由地址
          #uri: http://localhost:8001
          #指定微服务名称(注册到eureka上的名称 lb代表负载均衡)
          uri: lb://cloud-payment-service
          predicates:
            # 断言，路径相匹配的进行路由
            - Path=/payment/lb/**
            # 断言 指定时间之后才可能访问这个地址信息
            - After=2020-04-13T21:49:56.964+08:00[Asia/Shanghai]

eureka:
  instance:
    instance-id: gateway-9527
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    # 表示是否将自己注册进 EurekaServer 默认为 true
    register-with-eureka: true
    # 是否从 EurekaServer 抓取已有的注册信息，默认为 true. 单节点无所谓，集群必须设置为 true，才能配置 ribbon 使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #eureka server的地址