server:
  port: 8004              #配置服务端口号

spring:
  application:
    name: cloud-provider-service     #服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver     #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
  cloud:
    zookeeper:
      connect-string: 192.168.1.18:2181,192.168.1.19:2181,192.168.1.20:2181    #zookeeper注册中心地址

mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.youyuan.springcloud.entities    #所有Entity别名类所在的包