server:
  port: 83
spring:
  application:
    name: order-service-nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # nacos 地 址


management:
  endpoints:
    web:
      exposure:
        include: "*"

#消费者要去访问的微服务名称(注册到nacos的服务提供者服务名)，此处为自定义的参数，用于测试RestTemplate访问服务提供者时传的地址
service-url:
  nacos-user-service: http://payment-service-nacos