server:
  port: 8001
spring:
  application:
    name: cloud-payment-hystrix-service

eureka:
  client:
    register-with-eureka: true            #表示 将自己注册到eureka server  默认是true
    fetch-registry: true                  #是否从eureka server提取已有的注册信息，默认true，单节点无所谓，但是集群必须设置true ribbon才能实现负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #eureka server的地址
  instance:
    instance-id: payment_hystrix_8001       #修改主机在eureka上显示的别名 默认是主机名+端口号  一般生产环境不需要使用
    prefer-ip-address: true        #通过ip注册到eureka上，鼠标放到主机名上可以显示主机的ip地址
    lease-renewal-interval-in-seconds: 1  #调整为服务提供者每隔1秒向注册中心发送一次心跳
    lease-expiration-duration-in-seconds: 2  #调整eureka服务在2秒内没有收到服务提供者发送心跳就从服务注册表中删除服务提供者的地址


#openfeign默认超时时间是1秒，默认内置了ribbon
ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000